name: Publish Crate

on:
  workflow_dispatch:
  push:
    # Pattern matched against refs/tags
    tags:
      - 'v*'
      - '!v*.*.*\+manual'  # Exclude tags that end with "+manual"

jobs:
  call-workflow-audit:
    uses: ./.github/workflows/audit.yml
  call-workflow-build:
    uses: ./.github/workflows/build.yml
  call-workflow-build-docs:
    uses: ./.github/workflows/build_docs.yml
  call-workflow-lint-and-test:
    uses: ./.github/workflows/lint_and_test.yml
  publish:
    name: Publish Crate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - uses: katyo/publish-crates@v2
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          ignore-unpublished-changes: true

